spring:
  datasource:
    url: jdbc:mysql://119.23.78.153:3306/transfer?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: Zsq20142149
    driver-class-name: com.mysql.jdbc.Driver