package com.zsq.datatransfer.mapper;

import com.zsq.datatransfer.model.TransferDatasource;
import com.zsq.datatransfer.model.TransferDatasourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransferDatasourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_datasource
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    long countByExample(TransferDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_datasource
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    int deleteByExample(TransferDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_datasource
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    int deleteByPrimaryKey(Integer datasourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_datasource
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    int insert(TransferDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_datasource
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    int insertSelective(TransferDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_datasource
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    List<TransferDatasource> selectByExample(TransferDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_datasource
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    TransferDatasource selectByPrimaryKey(Integer datasourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_datasource
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") TransferDatasource record, @Param("example") TransferDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_datasource
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    int updateByExample(@Param("record") TransferDatasource record, @Param("example") TransferDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_datasource
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    int updateByPrimaryKeySelective(TransferDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_datasource
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    int updateByPrimaryKey(TransferDatasource record);
}