package com.zsq.datatransfer.mapper;

import com.zsq.datatransfer.model.TransferProject;
import com.zsq.datatransfer.model.TransferProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransferProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_project
     *
     * @mbg.generated Thu Aug 08 15:36:56 CST 2019
     */
    long countByExample(TransferProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_project
     *
     * @mbg.generated Thu Aug 08 15:36:56 CST 2019
     */
    int deleteByExample(TransferProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_project
     *
     * @mbg.generated Thu Aug 08 15:36:56 CST 2019
     */
    int deleteByPrimaryKey(Integer projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_project
     *
     * @mbg.generated Thu Aug 08 15:36:56 CST 2019
     */
    int insert(TransferProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_project
     *
     * @mbg.generated Thu Aug 08 15:36:56 CST 2019
     */
    int insertSelective(TransferProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_project
     *
     * @mbg.generated Thu Aug 08 15:36:56 CST 2019
     */
    List<TransferProject> selectByExample(TransferProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_project
     *
     * @mbg.generated Thu Aug 08 15:36:56 CST 2019
     */
    TransferProject selectByPrimaryKey(Integer projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_project
     *
     * @mbg.generated Thu Aug 08 15:36:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") TransferProject record, @Param("example") TransferProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_project
     *
     * @mbg.generated Thu Aug 08 15:36:56 CST 2019
     */
    int updateByExample(@Param("record") TransferProject record, @Param("example") TransferProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_project
     *
     * @mbg.generated Thu Aug 08 15:36:56 CST 2019
     */
    int updateByPrimaryKeySelective(TransferProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_project
     *
     * @mbg.generated Thu Aug 08 15:36:56 CST 2019
     */
    int updateByPrimaryKey(TransferProject record);
}