package com.zsq.datatransfer.model;

public class TransferProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_project.project_id
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_project.project_name
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_project.url
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_project.file_id
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    private Integer fileId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_project.project_id
     *
     * @return the value of transfer_project.project_id
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_project.project_id
     *
     * @param projectId the value for transfer_project.project_id
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_project.project_name
     *
     * @return the value of transfer_project.project_name
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_project.project_name
     *
     * @param projectName the value for transfer_project.project_name
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_project.url
     *
     * @return the value of transfer_project.url
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_project.url
     *
     * @param url the value for transfer_project.url
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_project.file_id
     *
     * @return the value of transfer_project.file_id
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_project.file_id
     *
     * @param fileId the value for transfer_project.file_id
     *
     * @mbg.generated Thu Aug 08 10:16:48 CST 2019
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }
}