package com.zsq.datatransfer.model;

public class TransferDatasourceParam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_datasource_param.id
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_datasource_param.param_name
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    private String paramName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_datasource_param.datasource_id
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    private Integer datasourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_datasource_param.id
     *
     * @return the value of transfer_datasource_param.id
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_datasource_param.id
     *
     * @param id the value for transfer_datasource_param.id
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_datasource_param.param_name
     *
     * @return the value of transfer_datasource_param.param_name
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_datasource_param.param_name
     *
     * @param paramName the value for transfer_datasource_param.param_name
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_datasource_param.datasource_id
     *
     * @return the value of transfer_datasource_param.datasource_id
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    public Integer getDatasourceId() {
        return datasourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_datasource_param.datasource_id
     *
     * @param datasourceId the value for transfer_datasource_param.datasource_id
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    public void setDatasourceId(Integer datasourceId) {
        this.datasourceId = datasourceId;
    }
}