package com.zsq.datatransfer.model;

public class TransferFileType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_file_type.file_id
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_file_type.name
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_file_type.file_id
     *
     * @return the value of transfer_file_type.file_id
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_file_type.file_id
     *
     * @param fileId the value for transfer_file_type.file_id
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_file_type.name
     *
     * @return the value of transfer_file_type.name
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_file_type.name
     *
     * @param name the value for transfer_file_type.name
     *
     * @mbg.generated Thu Aug 08 21:26:35 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}